# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [j2v8]
        image-version: [2.0]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: sudo apt install git

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        aliyun_username: ${{ secrets.Aliyun_Username }}
        aliyun_password: ${{ secrets.Aliyun_Password }}
      run: |
        mkdir dock
        cd dock
        wget https://raw.githubusercontent.com/jinhan1414/mysitre/master/Dockerfile
        sudo docker login --username=${aliyun_username} registry.cn-chengdu.aliyuncs.com --password=${{ secrets.aliyun_password }}
        sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
        docker images
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} registry.cn-chengdu.aliyuncs.com/jinchengsong001/chengdu:${{ matrix.image-version }}
        sudo docker push registry.cn-chengdu.aliyuncs.com/jinchengsong001/chengdu:${{ matrix.image-version }}       
        
