# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: sudo apt install git

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=`pwd`/depot_tools:$PATH
        gclient
        fetch v8
        echo "target_os= ['android']">>.gclient
        cd v8
        gclient sync
        ./build/install-build-deps.sh
        git pull && gclient sync
        ./tools/dev/v8gen.py x64.release -vv
        rm out.gn/x64.release/args.gn
        cd out.gn/x64.release
        wget https://raw.githubusercontent.com/eclipsesource/J2V8/master/v8/android-x64/args.gn
        cd ../../
        ninja -C out.gn/x64.release -t clean
        # ninja -C out.gn/x64.release v8_monolith
        zip -q -r out.zip ./out.gn
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: out.zip
        # Directory containing files to upload
        path: ./
